#!/bin/bash

# set this to your active development branch
#develop_branch="dev"
#current_branch="$(git rev-parse --abbrev-ref HEAD)"

# only check commit messages on main development branch
#[ "$current_branch" != "$develop_branch" ] && exit 0

# Validate in commit msg
#commit='(JIRA-[0-9]+)'
commit='(JIRA-[0-9]+ (0[0-9]|1[0-9]|2[0-3])+:([0-5][0-9]|[0-5]+):([0-5][0-9]|[0-5]+))'
error_msg="Aborting commit. Your commit message is missing either a JIRA Issue ('JIRA-1111') AND the Effort ('HH:MM:SS')"

if ! grep -iqE "$commit" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
